version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: website_session_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_website_sessions')
                field: website_session_id
      - name: primary_product_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_products')
                field: product_id

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_orders')
                field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_products')
                field: product_id

  - name: stg_order_item_refunds
    columns:
      - name: order_item_refund_id
        tests:
          - unique
          - not_null
      - name: order_item_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_order_items')
                field: order_item_id
      - name: order_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_orders')
                field: order_id

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_name
        tests:
          - not_null

  - name: stg_website_pageviews
    columns:
      - name: website_pageview_id
        tests:
          - unique
          - not_null
      - name: website_session_id
        tests:
          - not_null
          - relationships:
              arguments: 
                to: ref('stg_website_sessions')
                field: website_session_id

  - name: stg_website_sessions
    columns:
      - name: website_session_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null