version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders
      - name: order_items
      - name: order_item_refunds
      - name: products
      - name: website_sessions
      - name: website_pageviews
      
